sudo: false
dist: trusty
language: c++ 

compiler: 
  - gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-7
    packages:
    - g++-6
    - clang 
    - llvm
    - cmake
    - libelf-dev 
    - ninja

cache:
  directories:
    - DEPENDS
    - TEMP

  env:
  - BUILD=RELEASE 
  - TARGET_ARCH=linux64 
  - SYSTEMC=systemc-2.3.3
  - LLVMCONFIG=llvm-config
  - LLVM_LD_FLAGS=`$LLVMCONFIG --ldflags`
  - CXX=/usr/bin/g++-6

install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC=systemc-2.3.3; export TARGET_ARCH=linux64; export BUILD=RELEASE
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - LLVMCONFIG --ldflags
  - echo $SYSTEMC_HOME
  - echo $LLVM_LD_FLAGS
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget https://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++11"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - cd ..

before_script:
  #  - mkdir BUILD && cd BUILD
  # - cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export SYSTEMC=$SYSTEMC_HOME/
  - export LLVM_CXX_FLAGS=(eval $LLVMCONFIG --cxxflags)
  - export LLVM_CXX_FLAGS="$LLVM_CXX_FLAGS -fvisibility-inlines-hidden -fno-aligned-allocation -Wsign-compare"
  - export LLVM_LIBS=(eval $LLVMCONFIG --libs)
    #- export LLVM_LD_FLAGS=(eval $LLVMCONFIG --ldflags)
    #- export LLVM_LD_FLAGS=(echo $LLVM_LD_FLAGS | sed 's/ *$//g')
  - mkdir -p TEMP; cd TEMP;
  - cmake ../ && make 
