sudo: false
dist: trusty
language: c++ 

compiler: 
  - gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - cmake
    - libelf-dev 

cache:
  directories:
    - DEPENDS

  env:
  - BUILD=RELEASE 
  - TARGET_ARCH=linux64 
  - SYSTEMC=systemc-2.3.3

install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC=systemc-2.3.3; export TARGET_ARCH=linux64; export BUILD=RELEASE
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - echo $SYSTEMC_HOME
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget https://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++11"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - cd ..

before_script:
  - mkdir BUILD && cd BUILD
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD

script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CXX=/usr/bin/g++-6
    export SYSTEMC=/usr/local/include/systemc
  - mkdir build; cd build;
  - cmake ../ && make 
