dist: focal
language: c++

services:
  - docker

branches:
  only:
    - master


before_install:
  - docker pull rseac/systemc-clang:clang-11.0.0

script:
  # setup environment and build executables and tests
  - docker run -v ${TRAVIS_BUILD_DIR}:/systemc-clang rseac/systemc-clang:clang-11.0.0 /bin/bash -c "cmake ../systemc-clang -DHDL=ON -DENABLE_VERILOG_TESTS=OFF -DENABLE_TESTS=ON -G \"Ninja\" && ninja &&  ctest" 

