dist: focal
language: c++

services:
  - docker

branches:
  only:
    - master

script:
  # setup environment and build executables and tests
  - echo "Setup the docker image"
  - docker image build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
  - echo "Run tests"
  - docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} ctest
