# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: "rseac/systemc-clang:clang-11.0.0"
      options: -v ${{github.workspace}}:/systemc-clang
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Print context
        # run: |
          # echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          # echo "github.workspace = ${{ github.workspace }}"
          # echo "$GITHUB_CONTEXT"
      # Runs a single command using the runners shell
      # - name: Run a one-line script
        # run: |
          # ls -l /systemc-clang/
#

      # Runs a set of commands using the runners shell
      - name: Build systemc-clang and run tests
        run: |
          cd /__w/ 
          mkdir systemc-clang-build 
          cd systemc-clang-build 
          cmake /systemc-clang -DHDL=ON -DENABLE_TESTS=ON -DENABLE_VERILOG_TESTS=ON -G Ninja && ninja && ctest --ouput-on-failure
        
